version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "09:00"
    timezone: Europe/London
  reviewers:
  - alexangas
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: gatsby-*
    versions:
    - ">= 0"
  - dependency-name: "@mdx-js/*"
    versions:
    - ">= 0"
  - dependency-name: netlify-cms-app
    versions:
    - ">= 0"
  - dependency-name: gatsby
    versions:
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
