# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'Set environment variables'
  inputs:
    script: 'export CI=true'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g gatsby-cli
  displayName: 'npm install gatsby-cli'

- script: |
    npm install
  displayName: 'npm install packages'

- script: |
    gatsby build
  displayName: 'gatsby build'

- task: PublishBuildArtifacts@1
  displayName: 'Public build artifacts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/public'
    ArtifactName: 'drop'
    publishLocation: 'Container'
