version: "3.7"

services:
    frontend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - /app/node_modules
        - .:/app
      environment:
        - NODE_ENV=development
        - GATSBY_WEBPACK_PUBLICPATH=/
        - CHOKIDAR_USEPOLLING=1
